export const arrayImages = [
  { id: "Apple", name: "🍎 Apple", path: "/img/apple.jfif" },
  { id: "Banana", name: "🍌 Banana", path: "/img/banana.jfif" },
  { id: "Strawberry", name: "🍓 Strawberry", path: "/img/strawberry.jfif" },
  { id: "Pineapple", name: "🍍 Pineapple", path: "/img/pineapple.jfif" },
  { id: "Mango", name: "🥭 Mango", path: "/img/mango.jfif" },
  { id: "Grapes", name: "🍇 Grapes", path: "/img/grapes.jfif" },
  { id: "Watermelon", name: "🍉 Watermelon", path: "/img/watermelon.jpg" },
  { id: "Orange", name: "🍊 Orange", path: "/img/orange.jfif" },
  { id: "Lemon", name: "🍋 Lemon", path: "/img/lemon.jfif" },
  { id: "Peach", name: "🍑 Peach", path: "/img/peach.jfif" },
  { id: "Cherries", name: "🍒 Cherries", path: "/img/cherries.jfif" },
  { id: "Pear", name: "🍐 Pear", path: "/img/pear.jfif" },
  { id: "Kiwi", name: "🥝 Kiwi", path: "/img/kiwi.jfif" },
  { id: "Coconut", name: "🥥 Coconut", path: "/img/coconut.jfif" },
  { id: "Blueberry", name: "🫐 Blueberry", path: "/img/blueberry.jfif" },
  { id: "Avocado", name: "🥑 Avocado", path: "/img/avocado.jfif" },
  { id: "Pomegranate", name: "🍈 Pomegranate", path: "/img/pomegranate.jfif" },
  { id: "Lime", name: "🟢 Lime", path: "/img/lime.jfif" },
  { id: "noimage", name: "🛇 No image", path: "/img/noimage.png" },
];
